server:
  port: 9000
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AnimeDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        show-sql: true
        format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB # 한 파일당 최대 용량 제한
      max-request-size: 50MB # 모든 파일의 최대 용량 제한
  data:
    web:
      pageable:
        default-page-size: 10 # 한 페이지당 게시글 수
        one-indexed-parameters: true # 페이지를 0부터 말고 1부터
        
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 271406145812-a4ul6gjtrlbsm61hgmua0ug0jgqf2a89.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

firebase:
  config:
    path: "src/main/resources/serviceAccountKey.json"  # 서비스 계정 파일의 경로를 설정


springdoc:
  api-docs:
    path: /api-docs
    # enabled: false
  swagger-ui:
    path: /swagger-ui.html
    # enabled: false

file:
  upload-dir: uploads/profile-images/
